service: support-bot

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events: 
      - http:
          method: 'post'
          path: 'submit-form'
